config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'comentarios/index'
  get 'comentarios/new'
  get 'comentarios/show'
  get 'comentarios/edit'
  get 'services/index'
  get 'services/new'
  get 'services/show'
  get 'services/edit'
  # get 'parties/index'
  # get 'parties/new'
  # get 'parties/show'
  # get 'parties/edit'
  # get 'comunas/index'
  # get 'comunas/show'
  # get 'comunas/edit'

  # CREATE COMUNA
  get 'comunas/new', to: 'comunas#new' #--> 'controlador#accion'
  post 'comunas', to: 'comunas#create'

  # READ COMUNA
  get 'comunas/index', to: 'comunas#index'
  get 'comunas/:id', to: 'comunas#show', as: 'comuna'

  # UPDATE COMUNA
  get 'comunas/:id/edit', to: 'comunas#edit', as: 'comuna_edit'
  patch 'comunas/:id', to: 'comunas#update', as: 'comuna_update'

  # DELETE COMUNA
  delete 'comunas/:id', to: 'comunas#delete'

  # CREATE PARTY
  get 'parties/new', to: 'parties#new'
  post 'parties', to: 'parties#create'

  # READ PARTY
  get 'parties/index', to: 'parties#index'
  get 'parties/:id', to: 'parties#show', as: 'party'

  # UPDATE PARTY
  get 'parties/:id/edit', to: 'parties#edit', as: 'party_edit'
  patch 'parties/:id', to: 'parties#update', as: 'party_update'

  # DELETE PARTY
  delete 'parties/:id', to: 'parties#delete'

  # CREATE SERVICE
  get 'services/new', to: 'services#new' #--> 'controlador#accion'
  post 'services', to: 'services#create'
  # READ SERVICE
  get 'services/index', to: 'services#index'
  get 'services/:id', to: 'services#show', as: 'service'
  # UPDATE SERVICE
  get 'services/:id/edit', to: 'services#edit', as: 'service_edit'
  patch 'services/:id', to: 'services#update', as: 'service_update'
  # DELETE SERVICE
  delete 'services/:id', to: 'services#delete'

  # CREATE COMMENT
  get 'comentarios/new', to: 'comentarios#new'
  post 'comentarios', to: 'comentarios#create'
  # READ COMMENNT
  get 'comentarios/index', to: 'comentarios#index'
  get 'comentarios/:id', to: 'comentarios#show', as: 'comentario'
  # UPDATE COMMENT
  get 'comentarios/:id/edit', to: 'comentarios#edit', as: 'comentario_edit'
  patch 'comentarios/:id', to: 'comentarios#update', as: 'comentario_update'
  # DELETE COMMENT
  delete 'comentarios/:id', to: 'comentarios#delete'

  #apuesta
  get 'parties/:id/bet', to: 'parties#bet', as: 'party_bet'
  post 'parties/:id/bet', to: 'parties#create_bet', as: 'party_create_bet'

  #update_apuesta
  get 'parties/:id/edit_bet', to: 'parties#edit_bet', as: 'party_edit_bet'
  patch 'parties/:id/edit_bet', to: 'parties#update_bet', as: 'party_update_bet'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  devise_scope :user do
    get "users/sessions/show", to: "users/sessions#show", as: "user_show_session"
    get "users/sessions/show_monedero", to: "users/sessions#show_monedero", as: "user_show_monedero"
    get "users/sessions/cargar_monedero", to: "users/sessions#cargar_monedero", as: "user_cargar_monedero"
    patch "users/sessions/patch_monedero", to: "users/sessions#patch_monedero", as: "user_patch_monedero"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'static_pages/home', to: 'static_pages#home'
  root to: 'static_pages#home'
end

app/models/service.rb
# frozen_string_literal: true

class Service < ApplicationRecord
  validates :nombre, presence: true
  validates :descripcion, presence: true
  validates :cap_max, presence: true, numericality: { only_interger: true }
  validates :precio, presence: true, numericality: { only_interger: true }
  validates :user_id, presence: true
  # validates :verified, presence: true
  has_many :comentarios, dependent: :destroy
  belongs_to :user
  has_and_belongs_to_many :comunas
  has_and_belongs_to_many :partys
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # para ver lo de las apuestas

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  # validates :admin, presence: false
  validates :monedero, presence: false
  # validates :image, presence: true
  has_one_attached :image
  has_many :assistants, dependent: :destroy
  has_many :partys, through: :assistants

  has_many :partys, dependent: :destroy
  has_many :comentarios, dependent: :destroy
  has_many :services, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/services_controller.rb
# frozen_string_literal: true

class ServicesController < ApplicationController
  def index
    @services = Service.all
  end

  def new
    @service = Service.new
  end

  def create
    @services_param = params.require(:service).permit(:nombre, :descripcion, :cap_max, :precio, :user_id, :verified, :valoracion, { comuna_ids: [] })
    @service = Service.create(@services_param)

    if @service.save
      redirect_to services_index_path, notice: 'Wow creaste tu service'
    else
      redirect_to services_new_path, notice: 'Error al crear tu service'
    end
  end

  def show
    @service = Service.find(params[:id])
    @comentario = Comentario.all
    @c_servicio = []
    @comentario.each do |comment|
      @c_servicio.append(comment) if @service.id == comment.service_id
    end
  end

  def edit
    @service = Service.find(params[:id])
  end

  def update
    @service = Service.find(params[:id])
    @services_param = params.require(:service).permit(:nombre, :descripcion, :cap_max, :precio, :verified, :valoracion, { comuna_ids: [] })

    if @service.update(@services_param)
      redirect_to services_index_path, notice: 'Service editada con exito'
    else
      redirect_to service_path(@service.id), notice: 'Error al editar servicio rey'
    end
  end

  def delete
    @service = Service.find(params[:id])
    @service.destroy
    redirect_to services_index_path
  end
end

app/helpers/services_helper.rb
# frozen_string_literal: true

module ServicesHelper
end

app/views/services/edit.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <%= link_to "Inicio", static_pages_home_path, class:"navbar-item" %>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          Carretes
        </a>
        <div class="navbar-dropdown">
          <%= link_to "Ver carretes", parties_index_path, class:"navbar-item"%>
          <% if current_user and not current_user.admin %>
          <%= link_to "Crear carrete", parties_new_path, class:"navbar-item"%>
          <% end %>
        </div>
      </div>

      <% if current_user %>
      <% if current_user.admin %>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          Comunas
        </a>
        <div class="navbar-dropdown">
          <%= link_to "Ver comunas", comunas_index_path, class:"navbar-item"%>

          <%= link_to "Crear comuna", comunas_new_path, class:"navbar-item"%>
        </div>
      </div>
      <% end %>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          Servicios
        </a>
        <div class="navbar-dropdown">
          <%= link_to "Ver servicios", services_index_path, class:"navbar-item"%>
          <% if not current_user.admin %>
          <%= link_to "Crear servicio", services_new_path, class:"navbar-item"%>
          <% end %>
        </div>
      </div>
    <% end %>
    </div>
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <% if not current_user %>
          <%= link_to 'Registrarse', new_user_registration_path, class:"button is-link" %> 
          <%= link_to 'Iniciar sesión', new_user_session_path, class:"button is-link" %> 
          <% else %> 
            <% if not current_user.admin %>
            <%= link_to "Mi perfil", user_show_session_path, class:"button is-link" %> 
            <% end %>
          <%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete, class:"button is-link" %> 
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>


<section class="hero is-link is-fullheight-with-navbar">
<div class="hero-body">
<div class="container">

<div class="columns">
  <div class="column">
    
  </div>
<div class="column">
<h1 class="title">
Editar servicio
</h1>

<%= form_with(model: @service, method: :patch, html: {class: 'box'}) do |form| %>

    <div class="field is-horizontal">
      <div class="field-label is-normal">
        <label class="label is normal">Nombre</label>
      </div>
      <div class="field-body">
        <div class="field"> 
            <%=form.text_field :nombre, class:"input", placeholder: "Ponle nombre a tu servicio", required:true%>
        </div>
      </div>
    </div>

    <div class="field is-horizontal">
      <div class="field-label is-normal">
        <label class="label is normal">Descripción</label>
      </div>
      <div class="field-body">
        <div class="field"> 
            <%=form.text_field :descripcion, class:"input", placeholder: "Describe que hace tu servicio", required:true%>
        </div>
      </div>
    </div>

    <div class="field is-horizontal">
      <div class="field-label is-normal">
        <label class="label is normal">Capacidad</label>
      </div>
      <div class="field-body">
        <div class="field"> 
            <%=form.number_field :cap_max, class:"input", placeholder: "Ingresa la capacidad máxima del servicio", required:true%>
        </div>
      </div>
    </div>

    <div class="field is-horizontal">
      <div class="field-label is-normal">
        <label class="label">Comunas</label>
      </div>
      <div class="field-body">
        <div class="field"> 
          <div class="control"> 
            <% for comuna in Comuna.all %>
              <div>
                  <%= hidden_field_tag "service[comuna_ids][]", '' %>
                  <%= check_box_tag "service[comuna_ids][]", comuna.id, @service.comunas.include?(comuna) %>
                  <%= comuna.nombre %> 
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="field is-horizontal">
      <div class="field-label is-normal">
        <label class="label">Precio</label>
      </div>
      <div class="field-body">
        <div class="field is-expanded">
          <div class="field has-addons">
            <div class="control">
              <div class="button is-static">
                $
              </div>
            </div>
            <div class="control is-expanded">
              <%=form.number_field :precio, class:"input", placeholder: "Ingresa el valor del servicio", required:true %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <% if not @service.verified and current_user.admin %>
        <div class="field"> 
        <%= form.check_box :verified,{class:"form-check-input", type:"checkbox"}, true, false %>
        <%=form.label :verified, 'Verificar'%>
        </div>

    <% end %>
    <div class="actions"> 
        <%=form.submit "Actualizar", class:"button is-success" %>
    </div>

<% end %>


</div>
  <div class="column">
    
  </div>

</div>


</div>
</div>
</section>

app/views/services/index.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <%= link_to "Inicio", static_pages_home_path, class:"navbar-item" %>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          Carretes
        </a>
        <div class="navbar-dropdown">
          <%= link_to "Ver carretes", parties_index_path, class:"navbar-item"%>
          <% if current_user and not current_user.admin %>
          <%= link_to "Crear carrete", parties_new_path, class:"navbar-item"%>
          <% end %>
        </div>
      </div>

      <% if current_user %>
      <% if current_user.admin %>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          Comunas
        </a>
        <div class="navbar-dropdown">
          <%= link_to "Ver comunas", comunas_index_path, class:"navbar-item"%>

          <%= link_to "Crear comuna", comunas_new_path, class:"navbar-item"%>
        </div>
      </div>
      <% end %>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          Servicios
        </a>
        <div class="navbar-dropdown">
          <%= link_to "Ver servicios", services_index_path, class:"navbar-item"%>
          <% if not current_user.admin %>
          <%= link_to "Crear servicio", services_new_path, class:"navbar-item"%>
          <% end %>
        </div>
      </div>
    <% end %>
    </div>
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <% if not current_user %>
          <%= link_to 'Registrarse', new_user_registration_path, class:"button is-link" %> 
          <%= link_to 'Iniciar sesión', new_user_session_path, class:"button is-link" %> 
          <% else %> 
            <% if not current_user.admin %>
            <%= link_to "Mi perfil", user_show_session_path, class:"button is-link" %> 
            <% end %>
          <%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete, class:"button is-link" %> 
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>


<section class="hero is-link is-fullheight-with-navbar">
<div class="hero-body">
<div class="container">

<% if not current_user.admin and not current_user.services.empty?%>

<h1 class="title">
Mis Servicios
</h1>

<div class="columns is-multiline">
  <% @services.each do |service| %>
  <% if current_user.services.exists?(service.id)%>
  <div class="column is-one-quarter">
    <div class="card">
        <div class="card-content">
          <div class="content">
            <% if not service.verified%>
              <h5 class="title has-text-danger"> NO VERIFICADO</h5>
            <% elsif service.verified%>
              <h5 class="title has-text-success"> VERIFICADO</h5>
            <% end %>
            <h3 class="title has-text-black-bis"> <%= service.nombre %></h3>
            Descripción: <%= service.descripcion %> <br/>
            Capacidad máxima: <%= service.cap_max %> <br/>
            Precio: $<%= service.precio %> <br/> <br/>
            <p style="text-align:center;">
            <%= link_to "Detalles", service_path(service.id), class: "button is-link"%>
            <%= link_to "Editar", service_edit_path(service.id), class: "button is-warning"%>
            <%= link_to "Eliminar", service_path(service.id), method: :delete, class: "button is-danger", data: { confirm: "¿Estás seguro?" }%>
            </p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <% end %>
</div>

<% end %>

<h1 class="title">
Servicios
</h1>

<div class="columns is-multiline">
  <% cantidad = 0 %>
  <% @services.each do |service| %>
  <% if (not current_user.services.exists?(service.id) and service.verified) or current_user.admin%>
  <% cantidad = 1 %>
  <div class="column is-one-quarter">
    <div class="card">
        <div class="card-content">
          <div class="content">
            <% if current_user.admin%>
              <% if not service.verified%>
                <h5 class="title has-text-danger"> NO VERIFICADO</h5>
              <% elsif service.verified%>
                <h5 class="title has-text-success"> VERIFICADO</h5>
              <% end %>
            <% end %>
            <h3 class="title has-text-black-bis"> <%= service.nombre %></h3>
            Descripción: <%= service.descripcion %> <br/>
            Capacidad máxima: <%= service.cap_max %> <br/>
            Precio: $<%= service.precio %> <br/> <br/>
            <% if current_user.admin%>
            <p style="text-align:center;">
            <%= link_to "Detalles", service_path(service.id), class: "button is-link"%>
            <%= link_to "Editar", service_edit_path(service.id), class: "button is-warning"%>
            <%= link_to "Eliminar", service_path(service.id), method: :delete, class: "button is-danger", data: { confirm: "¿Estás seguro?" }%>
            </p>
            <p style="text-align:center;">
            <% else %>
            <p style="text-align:center;">
            <%= link_to "Detalles", service_path(service.id), class: "button is-link"%>
            
            <% carretes = Party.all %>
            <% contador = 0 %>
            <% carretes.each do |carrete| %>
              <% if carrete.service_ids.include?(service.id)%>
                <% asistentes = Assistant.where("party_id = ?", carrete.id)%>
                <% asistentes.each do |persona|%> 
                  <% persona_asistente = User.find(persona.user_id)%>
                  <% if (carrete.user_id == current_user.id or persona_asistente.id == current_user.id) and Date.today >= carrete.fecha and carrete.hacer and contador == 0%>
                    <%= link_to "Comentar", comentarios_new_path(service_id: service.id), class: "button is-success"%>
                    <% contador = 1 %>
                    <% break %>
                    <% break %>
                  <% end %>
                <% end %>
              <% end %>
            <% end %>
            </p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <% end %>
  <% if cantidad != 1 %>
    <h1 class="subtitle">No hay servicios que mostrar.</h1>
  <% end %>
</div>


</div>
</div>
</section>

app/views/services/new.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <%= link_to "Inicio", static_pages_home_path, class:"navbar-item" %>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          Carretes
        </a>
        <div class="navbar-dropdown">
          <%= link_to "Ver carretes", parties_index_path, class:"navbar-item"%>
          <% if current_user and not current_user.admin %>
          <%= link_to "Crear carrete", parties_new_path, class:"navbar-item"%>
          <% end %>
        </div>
      </div>

      <% if current_user %>
      <% if current_user.admin %>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          Comunas
        </a>
        <div class="navbar-dropdown">
          <%= link_to "Ver comunas", comunas_index_path, class:"navbar-item"%>

          <%= link_to "Crear comuna", comunas_new_path, class:"navbar-item"%>
        </div>
      </div>
      <% end %>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          Servicios
        </a>
        <div class="navbar-dropdown">
          <%= link_to "Ver servicios", services_index_path, class:"navbar-item"%>
          <% if not current_user.admin %>
          <%= link_to "Crear servicio", services_new_path, class:"navbar-item"%>
          <% end %>
        </div>
      </div>
    <% end %>
    </div>
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <% if not current_user %>
          <%= link_to 'Registrarse', new_user_registration_path, class:"button is-link" %> 
          <%= link_to 'Iniciar sesión', new_user_session_path, class:"button is-link" %> 
          <% else %> 
            <% if not current_user.admin %>
            <%= link_to "Mi perfil", user_show_session_path, class:"button is-link" %> 
            <% end %>
          <%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete, class:"button is-link" %> 
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>


<section class="hero is-link is-fullheight-with-navbar">
<div class="hero-body">
  <div class="container">

<div class="columns is-mobile is-centered">
<div class="column is-half">

    <h1 class="title">
    Crear servicio
    </h1>

      <%= form_with(model: @service, method: :post, html: {class: 'box'}) do |form| %>

          <div class="field is-horizontal">
            <div class="field-label is-normal">
              <label class="label is normal">Nombre</label>
            </div>
            <div class="field-body">
              <div class="field"> 
                  <%=form.text_field :nombre, class:"input", placeholder: "Ponle nombre a tu servicio", required:true%>
              </div>
            </div>
          </div>

          <div class="field is-horizontal">
            <div class="field-label is-normal">
              <label class="label is normal">Descripción</label>
            </div>
            <div class="field-body">
              <div class="field"> 
                  <%=form.text_field :descripcion, class:"input", placeholder: "Describe que hace tu servicio", required:true%>
              </div>
            </div>
          </div>

          <div class="field is-horizontal">
            <div class="field-label is-normal">
              <label class="label is normal">Capacidad</label>
            </div>
            <div class="field-body">
              <div class="field"> 
                  <%=form.number_field :cap_max, class:"input", placeholder: "Ingresa la capacidad máxima del servicio", required:true%>
              </div>
            </div>
          </div>

          <div class="field is-horizontal">
            <div class="field-label is-normal">
              <label class="label">Comunas</label>
            </div>
            <div class="field-body">
              <div class="field"> 
                <div class="control"> 
                  <% for comuna in Comuna.all %>
                    <div>
                        <%= check_box_tag "service[comuna_ids][]", comuna.id, @service.comunas.include?(comuna) %>
                        <%= comuna.nombre %> 
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>

          <div class="field is-horizontal">
            <div class="field-label is-normal">
              <label class="label">Precio</label>
            </div>
            <div class="field-body">
              <div class="field is-expanded">
                <div class="field has-addons">
                  <div class="control">
                    <div class="button is-static">
                      $
                    </div>
                  </div>
                  <div class="control is-expanded">
                    <%=form.number_field :precio, class:"input", placeholder: "Ingresa el valor del servicio", required:true %>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="field">
              <%= form.hidden_field :user_id, :value => current_user.id%>
          </div> 

          <div class="field is-horizontal">
            <div class="field-label">
            </div>
            <div class="field-body">
              <div class="field">
                <div class="action">
                  <%=form.submit "Crear servicio", class: "button is-success" %>
                </div>
              </div>
            </div>
          </div>
          
      <% end %>

    
</div>
</div>


</div>
</div>
</section>

app/views/services/show.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <%= link_to "Inicio", static_pages_home_path, class:"navbar-item" %>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          Carretes
        </a>
        <div class="navbar-dropdown">
          <%= link_to "Ver carretes", parties_index_path, class:"navbar-item"%>
          <% if current_user and not current_user.admin %>
          <%= link_to "Crear carrete", parties_new_path, class:"navbar-item"%>
          <% end %>
        </div>
      </div>

      <% if current_user %>
      <% if current_user.admin %>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          Comunas
        </a>
        <div class="navbar-dropdown">
          <%= link_to "Ver comunas", comunas_index_path, class:"navbar-item"%>

          <%= link_to "Crear comuna", comunas_new_path, class:"navbar-item"%>
        </div>
      </div>
      <% end %>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          Servicios
        </a>
        <div class="navbar-dropdown">
          <%= link_to "Ver servicios", services_index_path, class:"navbar-item"%>
          <% if not current_user.admin %>
          <%= link_to "Crear servicio", services_new_path, class:"navbar-item"%>
          <% end %>
        </div>
      </div>
    <% end %>
    </div>
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <% if not current_user %>
          <%= link_to 'Registrarse', new_user_registration_path, class:"button is-link" %> 
          <%= link_to 'Iniciar sesión', new_user_session_path, class:"button is-link" %> 
          <% else %> 
            <% if not current_user.admin %>
            <%= link_to "Mi perfil", user_show_session_path, class:"button is-link" %> 
            <% end %>
          <%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete, class:"button is-link" %> 
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>


<section class="hero is-link is-fullheight-with-navbar">
<div class="hero-body">
  <div class="container">

<h1 class="title">
    Detalles
</h1>

<div class="columns">
  <div class="column">

    <div class="card">
      <div class="card-content">
          <div class="content">
          <h3 class="title has-text-black-bis"> <%= @service.nombre %></h3>
          Descripción: <%= @service.descripcion %> <br/>
          Capacidad máxima: <%= @service.cap_max %> <br/>
          Precio: $<%= @service.precio %> <br/>
          <% numero = 0 %>
          <% valoracion = 0 %>  
          <% @c_servicio.each do |comentario| %>
            <% numero += 1 %>
            <% valoracion += comentario.valoracion %>
          <% @service.valoracion = (valoracion/numero) %>  
          <% end %>
          Valoración promedio:
          <% for i in (1..@service.valoracion)%>
              &#11088;
            <% end %>
            </br>
          </div>
      </div>
    </div>
    <br/>

    <div class="card">
      <div class="card-content">
          <div class="content">
          <h3 class="title has-text-black-bis"> Comunas de operación </h3>
          <% for comuna in Comuna.all %>
            <% if @service.comuna_ids.include? comuna.id %>
              <div>
                  <%= comuna.nombre %>
              </div>
            <% end %>
          <% end %>
          </div>
      </div>
  </div>

</div>

  <div class="column">
  </div>
  <div class="column">
  </div>

</div>

<% if current_user.id == @service.user_id%>

<h1 class="title">
Carretes a asistir
</h1>
<div class="columns is-multiline">
  <% Party.all.each do |party| %>
  <% if party.service_ids.include? @service.id %>
  <div class="column is-one-quarter">
    <div class="card">
        <div class="card-content">
          <div class="content">
            <% if Date.today == party.fecha %>
              <h5 class="title has-text-info"> ES HOY </h5>
            <% elsif Date.today < party.fecha %>
              <h5 class="title has-text-success"> PRÓXIMO </h5>
            <% elsif Date.today > party.fecha %>
              <h5 class="title has-text-danger"> YA FUE </h5>
            <% end %>
            <h3 class="title has-text-black-bis"> <%= party.titulo %></h3>
            <% for comuna in Comuna.all %>
              <% if comuna.id == party.comuna_id %>
                Comuna: <%= comuna.nombre %> <br/>
              <% end %>
            <% end %>
            Dirección: <%= party.direccion %> <br/>
            Fecha: <%= party.fecha %> <br/>
            Capacidad: <%= party.capacidad %> <br/> <br/>
            <p style="text-align:center;">
            <%= link_to "Detalles", party_path(party.id), class: "button is-link"%>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <% end %>
</div>

<% end %>

<h1 class="title">
    Comentarios
</h1>

<div class="columns is-multiline">
  <% @c_servicio.each do |comentario| %>
  <div class="column is-one-quarter">
    <div class="card">
        <div class="message is-info">
        <div class="message-header">
        <% if comentario.user_id == current_user.id%>
          Tú
          <%= link_to "Eliminar", comentario_path(comentario.id), method: :delete, class: "delete", data: { confirm: "¿Estás seguro?" }%>
        <% end %>
        <% User.all.each do |usuario| %>
          <% if usuario.id == comentario.user_id and comentario.user_id != current_user.id%>
            <%= usuario.first_name %> <%= usuario.last_name %>
            <% if current_user.admin%>
              <%= link_to "Eliminar", comentario_path(comentario.id), method: :delete, class: "delete", data: { confirm: "¿Estás seguro?" }%>
            <% end %>
          <% end %>

        <% end %>
      </div>
          <div class="message-body">  
            <% for i in (1..comentario.valoracion)%>
              &#11088;
            <% end %>
            </br>
            <%= comentario.contenido %> </br>
            <%= comentario.created_at.strftime("%d-%m-%Y")%></br>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>


</div>
</div>
</section>