config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'comentarios/index'
  get 'comentarios/new'
  get 'comentarios/show'
  get 'comentarios/edit'
  get 'services/index'
  get 'services/new'
  get 'services/show'
  get 'services/edit'
  # get 'parties/index'
  # get 'parties/new'
  # get 'parties/show'
  # get 'parties/edit'
  # get 'comunas/index'
  # get 'comunas/show'
  # get 'comunas/edit'

  # CREATE COMUNA
  get 'comunas/new', to: 'comunas#new' #--> 'controlador#accion'
  post 'comunas', to: 'comunas#create'

  # READ COMUNA
  get 'comunas/index', to: 'comunas#index'
  get 'comunas/:id', to: 'comunas#show', as: 'comuna'

  # UPDATE COMUNA
  get 'comunas/:id/edit', to: 'comunas#edit', as: 'comuna_edit'
  patch 'comunas/:id', to: 'comunas#update', as: 'comuna_update'

  # DELETE COMUNA
  delete 'comunas/:id', to: 'comunas#delete'

  # CREATE PARTY
  get 'parties/new', to: 'parties#new'
  post 'parties', to: 'parties#create'

  # READ PARTY
  get 'parties/index', to: 'parties#index'
  get 'parties/:id', to: 'parties#show', as: 'party'

  # UPDATE PARTY
  get 'parties/:id/edit', to: 'parties#edit', as: 'party_edit'
  patch 'parties/:id', to: 'parties#update', as: 'party_update'

  # DELETE PARTY
  delete 'parties/:id', to: 'parties#delete'

  # CREATE SERVICE
  get 'services/new', to: 'services#new' #--> 'controlador#accion'
  post 'services', to: 'services#create'
  # READ SERVICE
  get 'services/index', to: 'services#index'
  get 'services/:id', to: 'services#show', as: 'service'
  # UPDATE SERVICE
  get 'services/:id/edit', to: 'services#edit', as: 'service_edit'
  patch 'services/:id', to: 'services#update', as: 'service_update'
  # DELETE SERVICE
  delete 'services/:id', to: 'services#delete'

  # CREATE COMMENT
  get 'comentarios/new', to: 'comentarios#new'
  post 'comentarios', to: 'comentarios#create'
  # READ COMMENNT
  get 'comentarios/index', to: 'comentarios#index'
  get 'comentarios/:id', to: 'comentarios#show', as: 'comentario'
  # UPDATE COMMENT
  get 'comentarios/:id/edit', to: 'comentarios#edit', as: 'comentario_edit'
  patch 'comentarios/:id', to: 'comentarios#update', as: 'comentario_update'
  # DELETE COMMENT
  delete 'comentarios/:id', to: 'comentarios#delete'

  #apuesta
  get 'parties/:id/bet', to: 'parties#bet', as: 'party_bet'
  post 'parties/:id/bet', to: 'parties#create_bet', as: 'party_create_bet'

  #update_apuesta
  get 'parties/:id/edit_bet', to: 'parties#edit_bet', as: 'party_edit_bet'
  patch 'parties/:id/edit_bet', to: 'parties#update_bet', as: 'party_update_bet'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  devise_scope :user do
    get "users/sessions/show", to: "users/sessions#show", as: "user_show_session"
    get "users/sessions/show_monedero", to: "users/sessions#show_monedero", as: "user_show_monedero"
    get "users/sessions/cargar_monedero", to: "users/sessions#cargar_monedero", as: "user_cargar_monedero"
    patch "users/sessions/patch_monedero", to: "users/sessions#patch_monedero", as: "user_patch_monedero"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'static_pages/home', to: 'static_pages#home'
  root to: 'static_pages#home'
end

app/models/party.rb
# frozen_string_literal: true

class Party < ApplicationRecord
  # para ver lo de las apuestas
  has_many :assistants, dependent: :destroy
  has_many :users, through: :assistants

  validates :titulo, presence: true
  validates :descripcion, presence: true
  validates :direccion, presence: true
  validates :capacidad, presence: true, numericality: { only_interger: true }
  validates :costo, presence: true, numericality: { only_interger: true }
  validates :user_id, presence: true
  validates :comuna_id, presence: true
  validates :code, presence: true

  belongs_to :user
  belongs_to :comuna
  has_and_belongs_to_many :services, dependent: :destroy
end

app/models/service.rb
# frozen_string_literal: true

class Service < ApplicationRecord
  validates :nombre, presence: true
  validates :descripcion, presence: true
  validates :cap_max, presence: true, numericality: { only_interger: true }
  validates :precio, presence: true, numericality: { only_interger: true }
  validates :user_id, presence: true
  # validates :verified, presence: true
  has_many :comentarios, dependent: :destroy
  belongs_to :user
  has_and_belongs_to_many :comunas
  has_and_belongs_to_many :partys
end

app/controllers/parties_controller.rb
# frozen_string_literal: true

class PartiesController < ApplicationController
  def index
    @parties = Party.all
  end

  def new
    @party = Party.new
    @comunas = Comuna.all
    @service_all = Service.all
    @lista = []
    @comunas.each do |comuna|
      @lista.append(comuna.id)
    end
  end

  def create
    @parties_param = params.require(:party).permit(:titulo, :descripcion, :fecha, :direccion, :capacidad, :costo, :user_id, :comuna_id, :code, { service_ids: [] }, :revisado, :hacer)
    @party = Party.create(@parties_param)

    if @party.save
      redirect_to party_edit_path(@party.id)
    else
      redirect_to parties_new_path, notice: 'Error al crear tu party'
    end
  end

  def show
    @party = Party.find(params[:id])
    @usuarios = User.all
    @todos_los_asistentes = Assistant.all
    @mis_asistentes = []

    @todos_los_asistentes.each do |relacion|
      next unless relacion.party_id == @party.id

      @usuarios.each do |persona|
        if relacion.user_id == persona.id
          agregar = [persona.email, relacion.bet]
          @mis_asistentes.append(agregar)
        end
      end
    end

    @recaudado = Assistant.where('party_id = ?', @party.id).sum('bet')
  end

  def edit
    @party = Party.find(params[:id])
  end

  def update
    @party = Party.find(params[:id])
    @parties_param = params.require(:party).permit(:titulo, :descripcion, :fecha, :direccion, :capacidad, :costo, :user_id, :comuna_id, :code, { service_ids: [] })

    if @party.update(@parties_param)
      redirect_to parties_index_path
    else
      redirect_to party_edit_path(@party.id), notice: 'Error al editar party rey'
    end
  end

  def delete
    @party = Party.find(params[:id])
    @party.destroy
    redirect_to parties_index_path
  end

  def bet
    @assistant = Assistant.new
    @party = Party.find(params[:id])
  end

  def create_bet
    @party = Party.find(params[:id])
    @assistant_param = params.require(:assistant).permit(:bet, :user_id, :party_id)
    Rails.logger.debug " ######################### dinero actual #{current_user.monedero} #####################"
    Rails.logger.debug " ######################### cantidad que aposto #{@assistant_param[:bet]} #####################"
    if current_user.monedero >= @assistant_param[:bet].to_i
      @todos_los_asistentes = Assistant.all
      @mis_asistentes = []
      @menor = nil

      @todos_los_asistentes.each do |relacion|
        @mis_asistentes.append(relacion) if relacion.party_id == @party.id
      end
      # caso en que hay menos asistentes que el limite de cantidad
      if @mis_asistentes.length < @party.capacidad
        @assistant = Assistant.create(@assistant_param)
        current_user.monedero = current_user.monedero - @assistant_param[:bet].to_i
        if @assistant.save && current_user.save
          redirect_to parties_index_path
        else
          redirect_to party_bet_path(@party.id), notice: 'Error al hacer la apuesta'
        end
      else
        # caso cuando ya se alcanza la capacidad maxima del carrete
        @mis_asistentes.each do |relacion|
          if @menor.nil?
            @menor = relacion
          else
            @menor = relacion if @menor.bet > relacion.bet
          end
        end
        # en esta parte se compara si la apuesta que se acaba de hacer es mayor que la menor apuesta
        if @menor.bet < @assistant_param[:bet].to_i
          @devolver = nil
          User.all.each do |buscar|
            @devolver = buscar if buscar.id == @menor.user_id
          end
          @devolver.monedero = @devolver.monedero + @menor.bet
          current_user.monedero = current_user.monedero - @assistant_param[:bet].to_i
          redirect_to parties_index_path if @menor.update(@assistant_param) && current_user.save && @devolver.save
        else
          redirect_to party_bet_path(@party.id), notice: 'Caso que aun no veo'
        end
      end
    else
      redirect_to party_bet_path(@party.id), notice: 'NO TIENES EL DINERO SUFICIENTE'
      Rails.logger.debug '############# NO TIENES EL DINERO SUFICIENTE ##################'
    end
  end

  def edit_bet
    @party = Party.find(params[:id])
    @assistant = nil
    Assistant.all.each do |comparar|
      @assistant = comparar if (comparar.user_id == current_user.id) && (comparar.party_id == @party.id)
    end
  end

  def update_bet
    @party = Party.find(params[:id])
    @assistant_param = params.require(:assistant).permit(:bet, :user_id, :party_id)

    @assistant = nil
    Assistant.all.each do |comparar|
      @assistant = comparar if (comparar.user_id == current_user.id) && (comparar.party_id == @party.id)
    end

    if @assistant_param[:bet].to_i > @assistant.bet
      diferencia = @assistant_param[:bet].to_i - @assistant.bet
      current_user.monedero = current_user.monedero - diferencia.to_i
      redirect_to parties_index_path if @assistant.update(@assistant_param) && current_user.save
    elsif @assistant_param[:bet].to_i < @assistant.bet
      diferencia = @assistant.bet - @assistant_param[:bet].to_i
      current_user.monedero = current_user.monedero + diferencia.to_i
      redirect_to parties_index_path if @assistant.update(@assistant_param) && current_user.save
    else
      redirect_to party_edit_path(@party.id), notice: 'Error al editar la apuesta'
    end
  end
end

app/helpers/parties_helper.rb
# frozen_string_literal: true

module PartiesHelper
end

app/views/parties/bet.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <%= link_to "Inicio", static_pages_home_path, class:"navbar-item" %>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          Carretes
        </a>
        <div class="navbar-dropdown">
          <%= link_to "Ver carretes", parties_index_path, class:"navbar-item"%>
          <% if current_user and not current_user.admin %>
          <%= link_to "Crear carrete", parties_new_path, class:"navbar-item"%>
          <% end %>
        </div>
      </div>

      <% if current_user %>
      <% if current_user.admin %>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          Comunas
        </a>
        <div class="navbar-dropdown">
          <%= link_to "Ver comunas", comunas_index_path, class:"navbar-item"%>

          <%= link_to "Crear comuna", comunas_new_path, class:"navbar-item"%>
        </div>
      </div>
      <% end %>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          Servicios
        </a>
        <div class="navbar-dropdown">
          <%= link_to "Ver servicios", services_index_path, class:"navbar-item"%>
          <% if not current_user.admin %>
          <%= link_to "Crear servicio", services_new_path, class:"navbar-item"%>
          <% end %>
        </div>
      </div>
    <% end %>
    </div>
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <% if not current_user %>
          <%= link_to 'Registrarse', new_user_registration_path, class:"button is-link" %> 
          <%= link_to 'Iniciar sesión', new_user_session_path, class:"button is-link" %> 
          <% else %> 
            <% if not current_user.admin %>
            <%= link_to "Mi perfil", user_show_session_path, class:"button is-link" %> 
            <% end %>
          <%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete, class:"button is-link" %> 
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>


<section class="hero is-link is-fullheight-with-navbar">
<div class="hero-body">
<div class="container">

<div class="columns is-mobile is-centered">
<div class="column is-half">

<h1 class="title">
Apuesta
</h1>
    <%= form_with(model:@assistant, url: party_create_bet_path, method: :post, html: {class: 'box'}) do |form|%>

      <div class="field is-horizontal">
          <div class="field-label is-normal">
            <label class="label">Monedero</label>
          </div>
          <div class="field-body">
            <div class="field is-expanded">
              <div class="field has-addons">
                <div class="control is-expanded">
                  <div class="input" disabled>
                  <%= current_user.monedero%>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      <div class="field is-horizontal">
        <div class="field-label is-normal">
          <label class="label">Monto</label>
        </div>
        <div class="field-body">
          <div class="field is-expanded">
            <div class="field has-addons">
              <div class="control">
                <div class="button is-static">
                  $
                </div>
              </div>
              <div class="control is-expanded">
                <%=form.number_field :bet, class:"input", placeholder: "Dinero a cargar en la cuenta", required:true %>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="field">
      <%= form.hidden_field :user_id, :value => current_user.id%>
      </div>

      <div class="field">
      <%= form.hidden_field :party_id, :value => @party.id%>
      </div>

      <div class="field is-horizontal">
        <div class="field-label">
        </div>
        <div class="field-body">
          <div class="field">
            <div class="actions">
              <%=form.submit "Hacer apuesta", class: "button is-success" %>
            </div>
          </div>
        </div>
      </div>

    <% end %>


</div>
</div>
</section>

app/views/parties/edit.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <%= link_to "Inicio", static_pages_home_path, class:"navbar-item" %>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          Carretes
        </a>
        <div class="navbar-dropdown">
          <%= link_to "Ver carretes", parties_index_path, class:"navbar-item"%>
          <% if current_user and not current_user.admin %>
          <%= link_to "Crear carrete", parties_new_path, class:"navbar-item"%>
          <% end %>
        </div>
      </div>

      <% if current_user %>
      <% if current_user.admin %>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          Comunas
        </a>
        <div class="navbar-dropdown">
          <%= link_to "Ver comunas", comunas_index_path, class:"navbar-item"%>

          <%= link_to "Crear comuna", comunas_new_path, class:"navbar-item"%>
        </div>
      </div>
      <% end %>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          Servicios
        </a>
        <div class="navbar-dropdown">
          <%= link_to "Ver servicios", services_index_path, class:"navbar-item"%>
          <% if not current_user.admin %>
          <%= link_to "Crear servicio", services_new_path, class:"navbar-item"%>
          <% end %>
        </div>
      </div>
    <% end %>
    </div>
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <% if not current_user %>
          <%= link_to 'Registrarse', new_user_registration_path, class:"button is-link" %> 
          <%= link_to 'Iniciar sesión', new_user_session_path, class:"button is-link" %> 
          <% else %> 
            <% if not current_user.admin %>
            <%= link_to "Mi perfil", user_show_session_path, class:"button is-link" %> 
            <% end %>
          <%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete, class:"button is-link" %> 
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>


<section class="hero is-link is-fullheight-with-navbar">
<div class="hero-body">
<div class="container">

<div class="columns is-mobile is-centered">
<div class="column is-half">


<% if @party.costo == -1%>

<h1 class="title">
Elección de servicios
</h1>

<%  @party.costo = nil %>

<%= form_with(model: @party, method: :patch, html: {class: 'box'}) do |form| %>

    <div class="field is-horizontal">
      <div class="field-label is-normal">
        <label class="label">Servicios</label>
      </div>
      <div class="field-body">
        <div class="field"> 
            <% for service in Service.all %>
              <% if service.verified and service.comuna_ids.include?(@party.comuna.id) and service.cap_max >= @party.capacidad %>
                <div>
                    <%= hidden_field_tag "party[service_ids][]", '' %>
                    <%= check_box_tag "party[service_ids][]", service.id, @party.services.include?(service) %>
                    <%= service.nombre %> ($<%= service.precio %>)
                </div>
              <% end %>
            <% end %>
        </div>
      </div>
    </div>

    <div class="field is-horizontal">
      <div class="field-label is-normal">
        <label class="label">Costo total</label>
      </div>
      <div class="field-body">
        <div class="field is-expanded">
          <div class="field has-addons">
            <div class="control">
              <div class="button is-static">
                $
              </div>
            </div>
            <div class="control is-expanded">
              <%=form.number_field :costo, class:"input", placeholder: "Considera los costos de los servicios y las ganancias que quieres", required:true %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="field is-horizontal">
      <div class="field-label">
      </div>
      <div class="field-body">
        <div class="field">
          <div class="actions">
            <%=form.submit "Crear carrete", class: "button is-success" %>
          </div>
        </div>
      </div>
    </div>

<% end %>

<% else%>

<h1 class="title">
Editar carrete
</h1>

<%= form_with(model: @party, method: :patch, html: {class: 'box'}) do |form| %>
    
    <div class="field is-horizontal">
      <div class="field-label is-normal">
        <label class="label is normal">Título</label>
      </div>
      <div class="field-body">
        <div class="field"> 
            <%=form.text_field :titulo, class:"input", placeholder: "Ponle nombre a tu carrete", required:true%>
        </div>
      </div>
    </div>

    <div class="field is-horizontal">
      <div class="field-label is-normal">
        <label class="label is normal">Código</label>
      </div>
      <div class="field-body">
        <div class="field"> 
            <%=form.text_field :code, class:"input", placeholder: "Escribe un código secreto para los asistentes de tu carrete", required:true%>
        </div>
      </div>
    </div>

    <div class="field is-horizontal">
      <div class="field-label is-normal">
        <label class="label">Descripción</label>
      </div>
      <div class="field-body">
        <div class="field"> 
          <div class="control"> 
            <%=form.text_area :descripcion, class:"textarea", placeholder: "Cuenta sobre tu carrete", required:true%>
          </div>
        </div>
      </div>
    </div>

    <div class="field is-horizontal">
      <div class="field-label is-normal">
        <label class="label">Fecha</label>
      </div>
      <div class="field-body">
        <div class="field"> 
          <div class="control"> 
            <%=form.date_field :fecha, class:"input", required:true%>
          </div>
        </div>
      </div>
    </div>

    <div class="field is-horizontal">
      <div class="field-label is-normal">
        <label class="label">Dirección</label>
      </div>
      <div class="field-body">
        <div class="field"> 
          <div class="control"> 
            <%=form.text_field :direccion, class:"input", placeholder: "Avenida Siempreviva 742", required:true%>
          </div>
        </div>
      </div>
    </div>

    <div class="field is-horizontal">
      <div class="field-label is-normal">
        <label class="label">Capacidad</label>
      </div>
      <div class="field-body">
        <div class="field"> 
          <div class="control"> 
            <%=form.number_field :capacidad, class:"input", placeholder: "100, 200... Lo que querai", required:true%>
          </div>
        </div>
      </div>
    </div>

    <div class="field is-horizontal">
      <div class="field-label is-normal">
        <label class="label">Servicios</label>
      </div>
      <div class="field-body">
        <div class="field"> 
            <% for service in Service.all %>
              <% if service.verified and service.comuna_ids.include?(@party.comuna.id) and service.cap_max >= @party.capacidad %>
                <div>
                    <%= hidden_field_tag "party[service_ids][]", '' %>
                    <%= check_box_tag "party[service_ids][]", service.id, @party.services.include?(service) %>
                    <%= service.nombre %> ($<%= service.precio %>)
                </div>
              <% end %>
            <% end %>
        </div>
      </div>
    </div>

    <div class="field is-horizontal">
      <div class="field-label is-normal">
        <label class="label">Costo total</label>
      </div>
      <div class="field-body">
        <div class="field is-expanded">
          <div class="field has-addons">
            <div class="control">
              <div class="button is-static">
                $
              </div>
            </div>
            <div class="control is-expanded">
              <%=form.number_field :costo, class:"input", placeholder: "Considera los costos de los servicios incluidos", required:true %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="field is-horizontal">
      <div class="field-label">
      </div>
      <div class="field-body">
        <div class="field">
          <div class="actions">
            <%=form.submit "Actualizar", class: "button is-success" %>
          </div>
        </div>
      </div>
    </div>


<% end %>
<% end %>



</div>
</div>
</section>

app/views/parties/index.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <%= link_to "Inicio", static_pages_home_path, class:"navbar-item" %>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          Carretes
        </a>
        <div class="navbar-dropdown">
          <%= link_to "Ver carretes", parties_index_path, class:"navbar-item"%>
          <% if current_user and not current_user.admin %>
          <%= link_to "Crear carrete", parties_new_path, class:"navbar-item"%>
          <% end %>
        </div>
      </div>

      <% if current_user %>
      <% if current_user.admin %>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          Comunas
        </a>
        <div class="navbar-dropdown">
          <%= link_to "Ver comunas", comunas_index_path, class:"navbar-item"%>

          <%= link_to "Crear comuna", comunas_new_path, class:"navbar-item"%>
        </div>
      </div>
      <% end %>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          Servicios
        </a>
        <div class="navbar-dropdown">
          <%= link_to "Ver servicios", services_index_path, class:"navbar-item"%>
          <% if not current_user.admin %>
          <%= link_to "Crear servicio", services_new_path, class:"navbar-item"%>
          <% end %>
        </div>
      </div>
    <% end %>
    </div>
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <% if not current_user %>
          <%= link_to 'Registrarse', new_user_registration_path, class:"button is-link" %> 
          <%= link_to 'Iniciar sesión', new_user_session_path, class:"button is-link" %> 
          <% else %> 
            <% if not current_user.admin %>
            <%= link_to "Mi perfil", user_show_session_path, class:"button is-link" %> 
            <% end %>
          <%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete, class:"button is-link" %> 
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>


<section class="hero is-link is-fullheight-with-navbar">
<div class="hero-body">
<div class="container">

<% if current_user%>

<% if not current_user.admin%>
<h1 class="title">
Mis próximos carretes
</h1>

<div class="columns is-multiline">
  <% cantidad = 0 %>
  <% @parties.each do |party| %>
    <% if party.user_id == current_user.id and Date.today < party.fecha %>
      <% cantidad = 1 %>
    <div class="column is-one-quarter">
      <div class="card">
          <div class="card-content">
            <div class="content">
              <h3 class="title has-text-black-bis"><%= party.titulo %></h3>
              <% for comuna in Comuna.all %>
                <% if comuna.id == party.comuna_id %>
                  Comuna: <%= comuna.nombre %> <br/>
                <% end %>
              <% end %>
              Dirección: <%= party.direccion %> <br/>
              Fecha: <%= party.fecha %> <br/>
              Capacidad: <%= party.capacidad %> <br/>
              Costos: $<%= party.costo %> <br/> <br/>
              <% if current_user %>
                <p style="text-align:center;">
                <%= link_to "Detalles", party_path(party.id), class: "button is-link"%>
                <%= link_to "Editar", party_edit_path(party.id), class: "button is-warning"%>
                <%= link_to "Eliminar", party_path(party.id), method: :delete, class: "button is-danger", data: { confirm: "¿Estás seguro?" }%>
                </p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
  <% if cantidad != 1 %>
    <h1 class="subtitle">No tienes carretes aún.</h1>
  <% end %>
</div>

<% end %>


<h1 class="title">
Todos los carretes disponibles
</h1>

<div class="columns is-multiline">
  <% @parties.each do |party| %>
  <% if party.user_id != current_user.id and Date.today <= party.fecha %>
  <% cantidad = 1 %>
  <div class="column is-one-quarter">
    <div class="card">
        <div class="card-content">
          <div class="content">
            <% if Date.today == party.fecha %>
              <h5 class="title has-text-info"> ES HOY </h5>
            <% elsif Date.today < party.fecha %>
              <h5 class="title has-text-success"> PRÓXIMO </h5>
            <% end %>
            <h3 class="title has-text-black-bis"> <%= party.titulo %></h3>
            <% for comuna in Comuna.all %>
              <% if comuna.id == party.comuna_id %>
                Comuna: <%= comuna.nombre %> <br/>
              <% end %>
            <% end %>
            Dirección: <%= party.direccion %> <br/>
            Fecha: <%= party.fecha %> <br/>
            Capacidad: <%= party.capacidad %> <br/> <br/>
            <% if current_user.admin and Date.today < party.fecha%>
                <p style="text-align:center;">
              <%= link_to "Detalles", party_path(party.id), class: "button is-link"%>
              <%= link_to "Editar", party_edit_path(party.id), class: "button is-warning"%>
              <%= link_to "Eliminar", party_path(party.id), method: :delete, class: "button is-danger", data: { confirm: "¿Estás seguro?" }%>
              </p>
            <% elsif not current_user.admin or Date.today >= party.fecha%>
            <p style="text-align:center;">
            <%= link_to "Detalles", party_path(party.id), class: "button is-link"%>
            <% apuesta = 0 %>
            <% Assistant.all.each do |carrete| %>
              <% if carrete.user_id == current_user.id and carrete.party_id == party.id%>
                <% if Date.today < party.fecha %>
                  <%= link_to "Volver a apostar", party_edit_bet_path(party.id), class: "button is-success"%>
                <% end %>
                <% apuesta = 1 %>
                <% break %>
                <% end %>
            <% end %>
            <% if apuesta == 0 and Date.today < party.fecha%>
              <%= link_to "Apostar", party_bet_path(party.id), class: "button is-success"%>
            <% end %>
            </p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  <% end %>
  <% if cantidad != 1 %>
    <h1 class="subtitle"> No tienes carretes disponibles.</h1>
  <% end %>
</div>

<% else %>

<h1 class="title">
Carretes
</h1>

<div class="columns is-multiline">
  <% @parties.each do |party| %>
  <% if Date.today <= party.fecha %>
  <div class="column is-one-quarter">
    <div class="card">
        <div class="card-content">
          <div class="content">
            <h3 class="title has-text-black-bis"> <%= party.titulo %></h3>
            <% for comuna in Comuna.all %>
              <% if comuna.id == party.comuna_id %>
                Comuna: <%= comuna.nombre %> <br/>
              <% end %>
            <% end %>
            Fecha: <%= party.fecha %> <br/>
            Capacidad: <%= party.capacidad %> <br/>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <% end %>
</div>


<% end %>


</div>
</div>
</section>