config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'comentarios/index'
  get 'comentarios/new'
  get 'comentarios/show'
  get 'comentarios/edit'
  get 'services/index'
  get 'services/new'
  get 'services/show'
  get 'services/edit'
  # get 'parties/index'
  # get 'parties/new'
  # get 'parties/show'
  # get 'parties/edit'
  # get 'comunas/index'
  # get 'comunas/show'
  # get 'comunas/edit'

  # CREATE COMUNA
  get 'comunas/new', to: 'comunas#new' #--> 'controlador#accion'
  post 'comunas', to: 'comunas#create'

  # READ COMUNA
  get 'comunas/index', to: 'comunas#index'
  get 'comunas/:id', to: 'comunas#show', as: 'comuna'

  # UPDATE COMUNA
  get 'comunas/:id/edit', to: 'comunas#edit', as: 'comuna_edit'
  patch 'comunas/:id', to: 'comunas#update', as: 'comuna_update'

  # DELETE COMUNA
  delete 'comunas/:id', to: 'comunas#delete'

  # CREATE PARTY
  get 'parties/new', to: 'parties#new'
  post 'parties', to: 'parties#create'

  # READ PARTY
  get 'parties/index', to: 'parties#index'
  get 'parties/:id', to: 'parties#show', as: 'party'

  # UPDATE PARTY
  get 'parties/:id/edit', to: 'parties#edit', as: 'party_edit'
  patch 'parties/:id', to: 'parties#update', as: 'party_update'

  # DELETE PARTY
  delete 'parties/:id', to: 'parties#delete'

  # CREATE SERVICE
  get 'services/new', to: 'services#new' #--> 'controlador#accion'
  post 'services', to: 'services#create'
  # READ SERVICE
  get 'services/index', to: 'services#index'
  get 'services/:id', to: 'services#show', as: 'service'
  # UPDATE SERVICE
  get 'services/:id/edit', to: 'services#edit', as: 'service_edit'
  patch 'services/:id', to: 'services#update', as: 'service_update'
  # DELETE SERVICE
  delete 'services/:id', to: 'services#delete'

  # CREATE COMMENT
  get 'comentarios/new', to: 'comentarios#new'
  post 'comentarios', to: 'comentarios#create'
  # READ COMMENNT
  get 'comentarios/index', to: 'comentarios#index'
  get 'comentarios/:id', to: 'comentarios#show', as: 'comentario'
  # UPDATE COMMENT
  get 'comentarios/:id/edit', to: 'comentarios#edit', as: 'comentario_edit'
  patch 'comentarios/:id', to: 'comentarios#update', as: 'comentario_update'
  # DELETE COMMENT
  delete 'comentarios/:id', to: 'comentarios#delete'

  #apuesta
  get 'parties/:id/bet', to: 'parties#bet', as: 'party_bet'
  post 'parties/:id/bet', to: 'parties#create_bet', as: 'party_create_bet'

  #update_apuesta
  get 'parties/:id/edit_bet', to: 'parties#edit_bet', as: 'party_edit_bet'
  patch 'parties/:id/edit_bet', to: 'parties#update_bet', as: 'party_update_bet'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  devise_scope :user do
    get "users/sessions/show", to: "users/sessions#show", as: "user_show_session"
    get "users/sessions/show_monedero", to: "users/sessions#show_monedero", as: "user_show_monedero"
    get "users/sessions/cargar_monedero", to: "users/sessions#cargar_monedero", as: "user_cargar_monedero"
    patch "users/sessions/patch_monedero", to: "users/sessions#patch_monedero", as: "user_patch_monedero"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'static_pages/home', to: 'static_pages#home'
  root to: 'static_pages#home'
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  before_action :check_party

  def home; end

  private

  def check_party
    Party.all.each do |carrete|
      next unless (Date.today == carrete.fecha) && (carrete.revisado == false)

      carrete.revisado = true
      carrete.save
      @recaudado = Assistant.where('party_id = ?', carrete.id).sum('bet')
      Rails.logger.debug "----- LA RECAUDACION DEL CARRETE #{carrete.id} es de #{@recaudado}------------"
      @costos = 0
      carrete.services.each do |servicio|
        @costos += servicio.precio
      end
      Rails.logger.debug "----- EL COSTO DEL CARRETE #{carrete.id} es de #{@costos}------------"
      if (@recaudado >= @costos) && (@recaudado >= carrete.costo) # se realiza el pago hacia los provedores de los ser y el resto al anfitrion del carrete
        carrete.hacer = true
        carrete.save
        Rails.logger.debug "----- EL CARRETE #{carrete.id} SE REALIZA------------"
        carrete.services.each do |servicio|
          @provedor = User.find(servicio.user_id)
          @provedor.monedero = @provedor.monedero + servicio.precio
          @provedor.save
        end
        @anfitrion = User.find(carrete.user_id)
        @anfitrion.monedero = @anfitrion.monedero + @recaudado - @costos
        @anfitrion.save
      else # no se hace el carrete y hay que devolver la plata
        @devolucion = Assistant.where('party_id = ?', carrete.id)
        @devolucion.each do |persona|
          @persona_devolucion = User.find(persona.user_id)
          @persona_devolucion.monedero = @persona_devolucion.monedero + persona.bet
          @persona_devolucion.save
        end
      end
    end
  end
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <%= link_to "Inicio", static_pages_home_path, class:"navbar-item" %>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          Carretes
        </a>
        <div class="navbar-dropdown">
          <%= link_to "Ver carretes", parties_index_path, class:"navbar-item"%>
          <% if current_user and not current_user.admin %>
          <%= link_to "Crear carrete", parties_new_path, class:"navbar-item"%>
          <% end %>
        </div>
      </div>

      <% if current_user %>
      <% if current_user.admin %>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          Comunas
        </a>
        <div class="navbar-dropdown">
          <%= link_to "Ver comunas", comunas_index_path, class:"navbar-item"%>

          <%= link_to "Crear comuna", comunas_new_path, class:"navbar-item"%>
        </div>
      </div>
      <% end %>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          Servicios
        </a>
        <div class="navbar-dropdown">
          <%= link_to "Ver servicios", services_index_path, class:"navbar-item"%>
          <% if not current_user.admin %>
          <%= link_to "Crear servicio", services_new_path, class:"navbar-item"%>
          <% end %>
        </div>
      </div>
    <% end %>
    </div>
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <% if not current_user %>
          <%= link_to 'Registrarse', new_user_registration_path, class:"button is-link" %> 
          <%= link_to 'Iniciar sesión', new_user_session_path, class:"button is-link" %> 
          <% else %> 
            <% if not current_user.admin %>
            <%= link_to "Mi perfil", user_show_session_path, class:"button is-link" %> 
            <% end %>
          <%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete, class:"button is-link" %> 
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

<section class="hero is-link is-fullheight-with-navbar">

<section class="hero is-primary">
  <div class="hero-body">
    <div class="container">
      <% if current_user %>
      <h1 class="title has-text-weight-bold">
      <p> Hola, <%= current_user.first_name %>  <%= current_user.last_name %> </p>
      </h1>
      <% else %> 
      <h1 class="title">
      Bienvenido a DCCarrete 
      </h1>
    <% end %>
    </div>
  </div>
</section>

<div class="hero-body">
  <div class="container">

<% if current_user %>
<% if not current_user.admin %>

<h1 class="title">
    <p>Tus propios carretes para hoy &#127881;</p>
</h1>
<div class="columns is-multiline">
  <% cantidad = 0 %>
  <% current_user.partys.each do |party| %>
    <% if party.user_id == current_user.id and Date.today == party.fecha%>
      <% cantidad = 1 %>
    <div class="column is-one-quarter">
      <div class="card">
          <div class="card-content">
            <div class="content">
              <% if party.hacer%>
              <h5 class="title has-text-success"> SI SE CUMPLIÓ LA RECAUDACIÓN </h5>
              <% elsif not party.hacer %>
              <h5 class="title has-text-danger"> NO SE CUMPLIÓ LA RECAUDACIÓN  </h5>
              <% end %>
              <h3 class="title has-text-black-bis"><%= party.titulo %></h3>
              <% for comuna in Comuna.all %>
                <% if comuna.id == party.comuna_id %>
                  Comuna: <%= comuna.nombre %> <br/>
                <% end %>
              <% end %>
              Dirección: <%= party.direccion %> <br/>
              Fecha: <%= party.fecha %> <br/>
              Capacidad: <%= party.capacidad %> <br/>
              Costos: $<%= party.costo %> <br/> <br/>
              <% if Date.today < party.fecha %>
                <p style="text-align:center;">
                <%= link_to "Detalles", party_path(party.id), class: "button is-link"%>
                <%= link_to "Editar", party_edit_path(party.id), class: "button is-warning"%>
                <%= link_to "Eliminar", party_path(party.id), method: :delete, class: "button is-danger", data: { confirm: "¿Estás seguro?" }%>
                </p>
              <% else %>
                <p style="text-align:center;">
                <%= link_to "Detalles", party_path(party.id), class: "button is-link"%>
                </p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
  <% if cantidad != 1 %>
    <h1 class="subtitle">No tienes carretes aún.</h1>
  <% end %>
</div>



<h1 class="title">
    <p>Tus carretes inscritos para hoy &#127881;</p>
</h1>
<div class="columns is-multiline">
  <% cantidad = 0 %>
  <% assistants = Assistant.all %>
  <% parties = Party.all %>
  <% assistants.each do |asistente| %>
    <% if current_user.id == asistente.user_id%>
      <% party = nil %>
      <% parties.each do |fiesta| %>
        <% if fiesta.id == asistente.party_id%>
          <% party = fiesta %>
        <% end %>
      <% end %>
      <% if Date.today == party.fecha and party.hacer%>
        <% cantidad = 1 %>
        <div class="column is-one-quarter">
        <div class="card">
            <div class="card-content">
              <div class="content">
                <h3 class="title has-text-black-bis"><%= party.titulo %></h3>
                <% for comuna in Comuna.all %>
                  <% if comuna.id == party.comuna_id %>
                    Comuna: <%= comuna.nombre %> <br/>
                  <% end %>
                <% end %>
                Dirección: <%= party.direccion %> <br/>
                Fecha: <%= party.fecha %> <br/>
                Capacidad: <%= party.capacidad %> <br/><br/>
                <% if current_user %>
                  <p style="text-align:center;">
                  <%= link_to "Detalles", party_path(party.id), class: "button is-link"%><br/><br/>
                  Código de ingreso:
                  </p>
                  <p style="text-align:center;", class="title has-text-black-bis">
                   <%= party.code %>
                  </p>
                <% end %>
              </div>
            </div>
        </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
  <% if cantidad != 1 %>
    <h1 class="subtitle">No tienes carretes para hoy</h1>
  <% end %>
</div>

<% end %>


<% else %>
  <p style="text-align:center;">
    <span style='font-size:100px;'>&#127882;</span>
    <span style='font-size:100px;'> &#127880;</span>
    <span style='font-size:100px;'>&#127882;</span>
    <span style='font-size:100px;'> &#127880;</span>
    <span style='font-size:100px;'>&#127882;</span>
    <span style='font-size:100px;'> &#127880;</span>
    <span style='font-size:100px;'>&#127882;</span> <br/> <br/><br/> <br/>
    <span style='font-size:150px;'>&#128378;</span>
  </p>
<% end %>

</div>
</div>
</section>