config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'comentarios/index'
  get 'comentarios/new'
  get 'comentarios/show'
  get 'comentarios/edit'
  get 'services/index'
  get 'services/new'
  get 'services/show'
  get 'services/edit'
  # get 'parties/index'
  # get 'parties/new'
  # get 'parties/show'
  # get 'parties/edit'
  # get 'comunas/index'
  # get 'comunas/show'
  # get 'comunas/edit'

  # CREATE COMUNA
  get 'comunas/new', to: 'comunas#new' #--> 'controlador#accion'
  post 'comunas', to: 'comunas#create'

  # READ COMUNA
  get 'comunas/index', to: 'comunas#index'
  get 'comunas/:id', to: 'comunas#show', as: 'comuna'

  # UPDATE COMUNA
  get 'comunas/:id/edit', to: 'comunas#edit', as: 'comuna_edit'
  patch 'comunas/:id', to: 'comunas#update', as: 'comuna_update'

  # DELETE COMUNA
  delete 'comunas/:id', to: 'comunas#delete'

  # CREATE PARTY
  get 'parties/new', to: 'parties#new'
  post 'parties', to: 'parties#create'

  # READ PARTY
  get 'parties/index', to: 'parties#index'
  get 'parties/:id', to: 'parties#show', as: 'party'

  # UPDATE PARTY
  get 'parties/:id/edit', to: 'parties#edit', as: 'party_edit'
  patch 'parties/:id', to: 'parties#update', as: 'party_update'

  # DELETE PARTY
  delete 'parties/:id', to: 'parties#delete'

  # CREATE SERVICE
  get 'services/new', to: 'services#new' #--> 'controlador#accion'
  post 'services', to: 'services#create'
  # READ SERVICE
  get 'services/index', to: 'services#index'
  get 'services/:id', to: 'services#show', as: 'service'
  # UPDATE SERVICE
  get 'services/:id/edit', to: 'services#edit', as: 'service_edit'
  patch 'services/:id', to: 'services#update', as: 'service_update'
  # DELETE SERVICE
  delete 'services/:id', to: 'services#delete'

  # CREATE COMMENT
  get 'comentarios/new', to: 'comentarios#new'
  post 'comentarios', to: 'comentarios#create'
  # READ COMMENNT
  get 'comentarios/index', to: 'comentarios#index'
  get 'comentarios/:id', to: 'comentarios#show', as: 'comentario'
  # UPDATE COMMENT
  get 'comentarios/:id/edit', to: 'comentarios#edit', as: 'comentario_edit'
  patch 'comentarios/:id', to: 'comentarios#update', as: 'comentario_update'
  # DELETE COMMENT
  delete 'comentarios/:id', to: 'comentarios#delete'

  #apuesta
  get 'parties/:id/bet', to: 'parties#bet', as: 'party_bet'
  post 'parties/:id/bet', to: 'parties#create_bet', as: 'party_create_bet'

  #update_apuesta
  get 'parties/:id/edit_bet', to: 'parties#edit_bet', as: 'party_edit_bet'
  patch 'parties/:id/edit_bet', to: 'parties#update_bet', as: 'party_update_bet'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  devise_scope :user do
    get "users/sessions/show", to: "users/sessions#show", as: "user_show_session"
    get "users/sessions/show_monedero", to: "users/sessions#show_monedero", as: "user_show_monedero"
    get "users/sessions/cargar_monedero", to: "users/sessions#cargar_monedero", as: "user_cargar_monedero"
    patch "users/sessions/patch_monedero", to: "users/sessions#patch_monedero", as: "user_patch_monedero"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'static_pages/home', to: 'static_pages#home'
  root to: 'static_pages#home'
end

app/models/comentario.rb
# frozen_string_literal: true

class Comentario < ApplicationRecord
  validates :contenido, presence: true
  validates :user_id, presence: true
  validates :service_id, presence: true
  belongs_to :user
  belongs_to :service
end

app/controllers/comentarios_controller.rb
# frozen_string_literal: true

class ComentariosController < ApplicationController
  def index
    @comentarios = Comentario.all
  end

  def new
    @comentario = Comentario.new(service_id: params[:service_id])
    @service = Service.find(params[:service_id])

    @services = Service.all
    @lista = []
    @services.each do |service|
      @lista.append(service.id)
    end
  end

  def create
    # tiempo = DateTime.now
    # fecha = current_time.strftime "%d/%m/%Y %H:%M"
    @comentarios_params = params.require(:comentario).permit(:contenido, :user_id, :service_id, :valoracion)
    @comentario = Comentario.create(@comentarios_params)

    if @comentario.save
      redirect_to service_path(@comentario.service_id)
    # esto sirve en vez de poner el path /comunas/new, pasaber usamos rails routes
    else
      redirect_to comentarios_new_path(service_id: @comentario.service_id)
    end
  end

  def show
    @comentario = Comentario.find(params[:id])
  end

  def edit
    @comentario = Comentario.find(params[:id])
  end

  def update
    @comentario = Comentario.find(params[:id])
    @comentarios_param = params.require(:comentario).permit(:contenido)

    if @comentario.update(@comentarios_param)
      redirect_to comentario_path(@comentario.id), notice: 'Comentario editada con exito'
    else
      redirect_to comentario_path(@comentario.id), notice: 'Error al editar comentario rey'
    end
  end

  def delete
    @comentario = Comentario.find(params[:id])
    @comentario.destroy
    redirect_to service_path(@comentario.service_id)
  end
end

app/helpers/comentarios_helper.rb
# frozen_string_literal: true

module ComentariosHelper
end

app/views/comentarios/edit.html.erb
<h1>Editar comentario</h1>

<p> <%= notice %> </p>

<%= form_with(model: @comentario, method: :patch) do |form| %>
    <div class="field"> 
        <%=form.label :contenido%>
        <%=form.text_field :contenido%>
    </div>
    <br>
    <div class="action"> 
        <%=form.submit%>
    </div>
<% end %>
<br>
<%= link_to "ver listado de comentario", comentarios_index_path%>

app/views/comentarios/index.html.erb
<h1>Mis Comentarios</h1>

<table>
    <thead>
        <tr>
            <th>Contenido</th>
            <th>Fecha</th>
        </tr>
    </thead>

    <tbody>
        <% @comentarios.each do |comentario| %>
            <tr>
                <td><%= comentario.contenido %></td>
                <td><%= comentario.created_at.strftime("%d-%m-%Y")%></td>
                <td><%= link_to "ver detalle", comentario_path(comentario.id)%></td>
            </tr>
            
        <% end %>
    </tbody>
</table>

<%= link_to "volver a agregar comentario", comentarios_new_path%><br>
<%= link_to "volver al inicio", static_pages_home_path%>

app/views/comentarios/new.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <%= link_to "Inicio", static_pages_home_path, class:"navbar-item" %>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          Carretes
        </a>
        <div class="navbar-dropdown">
          <%= link_to "Ver carretes", parties_index_path, class:"navbar-item"%>
          <% if current_user and not current_user.admin %>
          <%= link_to "Crear carrete", parties_new_path, class:"navbar-item"%>
          <% end %>
        </div>
      </div>

      <% if current_user %>
      <% if current_user.admin %>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          Comunas
        </a>
        <div class="navbar-dropdown">
          <%= link_to "Ver comunas", comunas_index_path, class:"navbar-item"%>

          <%= link_to "Crear comuna", comunas_new_path, class:"navbar-item"%>
        </div>
      </div>
      <% end %>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          Servicios
        </a>
        <div class="navbar-dropdown">
          <%= link_to "Ver servicios", services_index_path, class:"navbar-item"%>
          <% if not current_user.admin %>
          <%= link_to "Crear servicio", services_new_path, class:"navbar-item"%>
          <% end %>
        </div>
      </div>
    <% end %>
    </div>
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <% if not current_user %>
          <%= link_to 'Registrarse', new_user_registration_path, class:"button is-link" %> 
          <%= link_to 'Iniciar sesión', new_user_session_path, class:"button is-link" %> 
          <% else %> 
            <% if not current_user.admin %>
            <%= link_to "Mi perfil", user_show_session_path, class:"button is-link" %> 
            <% end %>
          <%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete, class:"button is-link" %> 
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>


<section class="hero is-link is-fullheight-with-navbar">
<div class="hero-body">
  <div class="container">

<div class="columns is-mobile is-centered">
<div class="column is-half">

<h1 class="title">
Crear comentario
</h1>

<%= form_with(model: @comentario, method: :post, html: {class: 'box'}) do |form|%>

    <div class="field is-horizontal">
      <div class="field-label is-normal">
        <label class="label">Comentario</label>
      </div>
      <div class="field-body">
        <div class="field"> 
          <div class="control"> 
            <%=form.text_area :contenido, class:"textarea", placeholder: "¡Déjanos tu opinión!", required:true%>
          </div>
        </div>
      </div>
    </div>

    <div class="field is-horizontal">
      <div class="field-label is-normal">
        <label class="label">Valoración</label>
      </div>
      <div class="field-body">
        <div class="field is-narrow">
          <div class="control">
            <div class="select is-fullwidth">
              <%= form.select :valoracion, [1,2,3,4,5] %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="field">
        <%= form.hidden_field :user_id, :value => current_user.id%>
    </div>
    
    <div class="field">
        <%= form.hidden_field :service_id%>
    </div>

    <div class="field is-horizontal">
      <div class="field-label">
      </div>
      <div class="field-body">
        <div class="field">
          <div class="actions">
            <%=form.submit "Comentar", class: "button is-success" %>
          </div>
        </div>
      </div>
    </div>

<% end %>



</div>
</div>
</section>

app/views/comentarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
    <strong>Contenido comentario:</strong>
    <%= @comentario.contenido%>
</p>
<p>
    <strong>Fecha comentario:</strong>
    <%= @comentario.created_at.strftime("%d-%m-%Y")%>
</p>
<%= link_to "ver listado de comentario", comentarios_index_path%>
<br>
<%= link_to "Editar comentario", comentario_edit_path%>
<br>
<%= link_to "Eliminar comentario", comentario_path, method: :delete%>